codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1
    wait_for_ci: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
