codecov:
  branch: main
  notify:
    after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
