antora:
  extensions:
    - require: antora-shiki-extension
      theme: github-light
      register_languages:
        - id: cypher
          scope_name: source.cypher
          grammar_path: ./docs/tools/grammars/cypher.tmLanguage.json
          alias: [cypher]
site:
  title: Neo4j Code Graph Docs
  start_page: neo4j-code-graph:ROOT:index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: ./docs/.antora/ui-bundle.zip
    snapshot: true
  supplemental_files: ./docs/supplemental-ui
asciidoc:
  attributes:
    page-origin-private: false
    source-highlighter: shiki
