site:
  title: Neo4j Code Graph
  start_page: neo4j-code-graph:ROOT:index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: ./docs/.antora/ui-bundle.zip
    snapshot: true
  supplemental_files: ./docs/supplemental-ui
asciidoc:
  attributes:
    page-origin-private: false
    source-highlighter: highlight.js
    toclevels: 3
    sectanchors: true
