name: Docs
on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'examples/**' ]
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build Antora site
        run: npx -y antora@3.1.7 docs/preview.yml --stacktrace --fetch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
