name: Docs
on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'examples/**' ]
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Show Antora version
        run: npx -y antora@3.1.7 --version
      - name: List docs tree
        run: |
          echo "Working directory: $(pwd)"
          ls -la
          echo "--- docs tree ---"
          ls -la docs || true
          echo "--- modules tree ---"
          ls -la docs/modules/ROOT || true
      - name: Build Antora site
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          set -e
          mkdir -p .antora
          # Build Antora default UI from source to avoid flaky binary downloads
          UI_DIR=.antora/ui-default
          UI_BUNDLE=.antora/ui-bundle.zip
          echo "Cloning Antora UI default..."
          git clone --depth 1 --branch v3.1.7 https://github.com/antora/antora-ui-default.git "$UI_DIR" || \
          git clone --depth 1 --branch v3.1.7 https://gitlab.com/antora/antora-ui-default.git "$UI_DIR"
          echo "Installing UI dependencies..."
          (cd "$UI_DIR" && npm ci --no-audit --no-fund)
          echo "Building UI bundle..."
          (cd "$UI_DIR" && npx gulp bundle)
          cp "$UI_DIR/build/ui-bundle.zip" "$UI_BUNDLE"
          test -s "$UI_BUNDLE" || { echo "UI bundle not produced"; exit 1; }
          npx -y antora@3.1.7 generate antora-playbook.yml --stacktrace --fetch --log-level debug
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
