name: Docs
on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'examples/**' ]
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Show Antora version
        run: npx -y antora@3.1.7 --version
      - name: List docs tree
        run: |
          echo "Working directory: $(pwd)"
          ls -la
          echo "--- docs tree ---"
          ls -la docs || true
          echo "--- modules tree ---"
          ls -la docs/modules/ROOT || true
      - name: Build Antora site
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          mkdir -p .antora
          # Try multiple mirrors to fetch the UI bundle deterministically
          set -e
          UI_BUNDLE=.antora/ui-bundle.zip
          URLS=(
            https://cdn.jsdelivr.net/npm/@antora/ui-default@3.1.7/dist/ui-bundle.zip
            https://unpkg.com/@antora/ui-default@3.1.7/dist/ui-bundle.zip
            https://registry.npmmirror.com/@antora/ui-default/-/ui-default-3.1.7.tgz
          )
          for u in "${URLS[@]}"; do
            echo "Attempting to fetch UI bundle from: $u"
            if [[ "$u" == *.tgz ]]; then
              # Fallback: download tarball and extract the dist/ui-bundle.zip
              curl -fsSL "$u" -o .antora/ui-default.tgz || continue
              tar -tzf .antora/ui-default.tgz | grep -q "dist/ui-bundle.zip" || continue
              tar -xzf .antora/ui-default.tgz -C .antora
              FOUND=$(find .antora -path "*/dist/ui-bundle.zip" | head -n 1)
              if [[ -n "$FOUND" ]]; then
                cp "$FOUND" "$UI_BUNDLE"
                break
              fi
            else
              curl -fsSL "$u" -o "$UI_BUNDLE" && break || true
            fi
          done
          test -s "$UI_BUNDLE" || { echo "Failed to fetch UI bundle from all mirrors"; exit 1; }
          npx -y antora@3.1.7 generate antora-playbook.yml --stacktrace --fetch --log-level debug
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
