name: Tests

on:
  push:
  pull_request:

env:
  NEO4J_URI: ${{ secrets.NEO4J_URI }}
  NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
  NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
  NEO4J_DATABASE: ${{ secrets.NEO4J_DATABASE }}

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt
          pip install -r config/dev-requirements.txt
      - name: Unit tests (no integration)
        run: |
          pytest tests/ -v --cov=src --cov-report=xml --cov-report=term-missing -k "not integration"
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: coverage.xml
          fail_ci_if_error: false

  integration:
    runs-on: ubuntu-latest
    needs: unit
    if: ${{ env.NEO4J_URI != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt
          pip install -r config/dev-requirements.txt
      - name: Run integration tests
        run: |
          pytest tests/ -v -m "integration"
