name: Tests

on:
  push:
  pull_request:

env:
  NEO4J_URI: ${{ secrets.NEO4J_URI }}
  NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
  NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
  NEO4J_DATABASE: ${{ secrets.NEO4J_DATABASE }}

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install -r requirements.txt
      - name: Unit tests (no integration)
        run: |
          pytest tests/ -v -k "not integration" --cov=src --cov-report=xml --cov-report=term-missing || true
          if [ ! -f coverage.xml ] && [ -f .coverage ]; then python -m coverage xml -o coverage.xml || true; fi
          echo "Listing workspace to show coverage.xml presence:" && ls -lah
      - name: Verify coverage report exists
        run: |
          ls -lh || true
          if [ ! -f coverage.xml ]; then echo "coverage.xml missing"; exit 1; fi
          head -n 5 coverage.xml || true
      - name: Upload coverage.xml as artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: false

  integration:
    runs-on: ubuntu-latest
    needs: unit
    if: ${{ env.NEO4J_URI != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt
          pip install -r config/dev-requirements.txt
      - name: Run integration tests
        run: |
          pytest tests/ -v -m "integration"
